In [8]:
import pandas as pd
import sqlite3
from google.colab import files

uploaded = files.upload()

file_name = next(iter(uploaded))
df = pd.read_excel(file_name)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
display(df.head())

Saving Dataset for Data Analytics (2).xlsx to Dataset for Data Analytics (2).xlsx
Dataset loaded successfully!
Dataset shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [9]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Number of rows: 1200
Number of columns: 14

Column names:
['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

Missing values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

Duplicate rows: 0

In [10]:
# Convert the date into a format SQLite can read
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime("%Y-%m-%d")

# Create the SQLite database
conn = sqlite3.connect("project3.db")

# Store the dataset as a SQL table named orders
df.to_sql("orders", conn, if_exists="replace", index=False)

print("SQL database created successfully!")
print("Table name: orders")

SQL database created successfully!
Table name: orders

In [11]:
query = """
SELECT *
FROM orders
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,None,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [12]:
query = """
SELECT OrderID, Product, Quantity, TotalPrice
FROM orders;
"""

display(pd.read_sql_query(query, conn))

        OrderID  Product  Quantity  TotalPrice
0     ORD200000  Monitor         5     2853.10
1     ORD200001    Phone         2      302.70
2     ORD200002   Tablet         5     2753.40
3     ORD200003    Chair         1      273.19
4     ORD200004  Printer         4     2504.04
...         ...      ...       ...         ...
1195  ORD201195     Desk         1      107.04
1196  ORD201196  Monitor         2     1325.06
1197  ORD201197   Tablet         2      873.68
1198  ORD201198    Chair         4     1050.08
1199  ORD201199   Tablet         4     2242.32

[1200 rows x 4 columns]

In [13]:
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
WHERE TotalPrice > 1000;
"""

display(pd.read_sql_query(query, conn))

       OrderID  Product  TotalPrice
0    ORD200000  Monitor     2853.10
1    ORD200002   Tablet     2753.40
2    ORD200004  Printer     2504.04
3    ORD200009     Desk     2037.52
4    ORD200010   Tablet     3129.85
..         ...      ...         ...
507  ORD201191     Desk     1505.72
508  ORD201192    Chair     1298.55
509  ORD201196  Monitor     1325.06
510  ORD201198    Chair     1050.08
511  ORD201199   Tablet     2242.32

[512 rows x 3 columns]

In [14]:
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10;
"""

display(pd.read_sql_query(query, conn))

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20
5  ORD200107  Printer     3353.75
6  ORD200326   Laptop     3352.40
7  ORD201065  Printer     3334.00
8  ORD201031    Phone     3322.55
9  ORD200463   Laptop     3313.90

In [15]:
query = """
SELECT Product, COUNT(*) AS NumberOfOrders
FROM orders
GROUP BY Product
ORDER BY NumberOfOrders DESC;
"""

display(pd.read_sql_query(query, conn))

   Product  NumberOfOrders
0  Printer             181
1   Tablet             179
2    Chair             178
3   Laptop             173
4     Desk             170
5  Monitor             163
6    Phone             156

In [16]:
query = """
SELECT Product,
       SUM(TotalPrice) AS TotalSales
FROM orders
GROUP BY Product
ORDER BY TotalSales DESC;
"""

display(pd.read_sql_query(query, conn))

   Product  TotalSales
0    Chair   195620.11
1  Printer   195612.61
2   Laptop   192126.56
3   Tablet   186568.95
4  Monitor   175651.41
5     Desk   167459.93
6    Phone   151722.39

In [17]:
query = """
SELECT Product,
       ROUND(AVG(TotalPrice), 2) AS AverageOrderValue
FROM orders
GROUP BY Product
ORDER BY AverageOrderValue DESC;
"""

display(pd.read_sql_query(query, conn))

   Product  AverageOrderValue
0   Laptop            1110.56
1    Chair            1098.99
2  Printer            1080.73
3  Monitor            1077.62
4   Tablet            1042.28
5     Desk             985.06
6    Phone             972.58

In [18]:
query = """
SELECT PaymentMethod,
       COUNT(*) AS NumberOfOrders,
       SUM(TotalPrice) AS TotalSales,
       ROUND(AVG(TotalPrice), 2) AS AverageOrderValue
FROM orders
GROUP BY PaymentMethod
ORDER BY NumberOfOrders DESC;
"""

display(pd.read_sql_query(query, conn))

  PaymentMethod  NumberOfOrders  TotalSales  AverageOrderValue
0        Online             258   262442.94            1017.22
1          Cash             246   259786.29            1056.04
2   Credit Card             234   263847.63            1127.55
3    Debit Card             232   232361.18            1001.56
4     Gift Card             230   246323.92            1070.97

In [19]:
query = """
SELECT OrderStatus,
       COUNT(*) AS NumberOfOrders,
       SUM(TotalPrice) AS TotalOrderValue
FROM orders
GROUP BY OrderStatus
ORDER BY NumberOfOrders DESC;
"""

display(pd.read_sql_query(query, conn))

  OrderStatus  NumberOfOrders  TotalOrderValue
0   Cancelled             250        276396.21
1    Returned             247        243277.70
2     Pending             237        256328.15
3     Shipped             235        246159.58
4   Delivered             231        242600.32

In [20]:
query = """
SELECT ReferralSource,
       COUNT(*) AS NumberOfOrders
FROM orders
WHERE ReferralSource = 'Instagram'
GROUP BY ReferralSource;
"""

display(pd.read_sql_query(query, conn))

  ReferralSource  NumberOfOrders
0      Instagram             259

In [21]:
query = """
SELECT Product,
       SUM(TotalPrice) AS TotalSales
FROM orders
GROUP BY Product
HAVING SUM(TotalPrice) > 180000
ORDER BY TotalSales DESC;
"""

display(pd.read_sql_query(query, conn))

   Product  TotalSales
0    Chair   195620.11
1  Printer   195612.61
2   Laptop   192126.56
3   Tablet   186568.95

In [22]:
query = """
SELECT strftime('%Y-%m', Date) AS OrderMonth,
       COUNT(*) AS NumberOfOrders,
       SUM(TotalPrice) AS TotalOrderValue
FROM orders
GROUP BY strftime('%Y-%m', Date)
ORDER BY OrderMonth;
"""

display(pd.read_sql_query(query, conn))

   OrderMonth  NumberOfOrders  TotalOrderValue
0     2023-01              47         56685.75
1     2023-02              37         40117.66
2     2023-03              43         48609.37
3     2023-04              31         27751.71
4     2023-05              49         63836.84
5     2023-06              45         49500.19
6     2023-07              44         42820.66
7     2023-08              51         54352.14
8     2023-09              29         29526.67
9     2023-10              47         52607.85
10    2023-11              41         43079.67
11    2023-12              46         43754.73
12    2024-01              32         38528.08
13    2024-02              32         36909.57
14    2024-03              36         36030.90
15    2024-04              50         49613.14
16    2024-05              34         27909.11
17    2024-06              53         68068.54
18    2024-07              43         42963.98
19    2024-08              28         31991.07
20    2024-09              44         39794.98
21    2024-10              31         37226.97
22    2024-11              35         32413.76
23    2024-12              41         38785.77
24    2025-01              27         29099.40
25    2025-02              37         35317.55
26    2025-03              49         39200.66
27    2025-04              32         31821.20
28    2025-05              37         43396.64
29    2025-06              49         53047.40

In [23]:
SELECT SUM(TotalPrice) AS TotalSales
FROM orders
WHERE TotalSales > 1000;

SyntaxError: invalid syntax (1729679267.py, line 1)

In [24]:
sql_code = """
-- Project 3: SQL Data Analysis

-- 1. Display selected columns
SELECT OrderID, Product, Quantity, TotalPrice
FROM orders;

-- 2. Filter orders
SELECT OrderID, Product, TotalPrice
FROM orders
WHERE TotalPrice > 1000;

-- 3. Highest-priced orders
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10;

-- 4. Count orders by product
SELECT Product, COUNT(*) AS NumberOfOrders
FROM orders
GROUP BY Product;

-- 5. Total sales by product
SELECT Product, SUM(TotalPrice) AS TotalSales
FROM orders
GROUP BY Product;

-- 6. Average order value
SELECT Product, ROUND(AVG(TotalPrice), 2) AS AverageOrderValue
FROM orders
GROUP BY Product;

-- 7. Payment method analysis
SELECT PaymentMethod, COUNT(*) AS NumberOfOrders,
       SUM(TotalPrice) AS TotalSales
FROM orders
GROUP BY PaymentMethod;

-- 8. Order status analysis
SELECT OrderStatus, COUNT(*) AS NumberOfOrders
FROM orders
GROUP BY OrderStatus;

-- 9. Referral source analysis
SELECT ReferralSource, COUNT(*) AS NumberOfOrders
FROM orders
GROUP BY ReferralSource;

-- 10. Products above a sales threshold
SELECT Product, SUM(TotalPrice) AS TotalSales
FROM orders
GROUP BY Product
HAVING SUM(TotalPrice) > 180000;

-- 11. Monthly order analysis
SELECT strftime('%Y-%m', Date) AS OrderMonth,
       COUNT(*) AS NumberOfOrders,
       SUM(TotalPrice) AS TotalOrderValue
FROM orders
GROUP BY strftime('%Y-%m', Date)
ORDER BY OrderMonth;
"""

with open("project3_queries.sql", "w", encoding="utf-8") as f:
    f.write(sql_code)

print("SQL file created successfully!")
files.download("project3_queries.sql")

SQL file created successfully!